### ISSUE TITLE
UPDATE WIKI!!!

### ISSUE THREAD

**Issue by Reischi** [Fachschaft07/fs-rest#32]
The wiki is on a very very very old state. Please fix this. PRONTO. Please. 
If not i can not work on the iOS-app.

**Comment by thomai** [comment]
What do you think about another kind of documentation than the github wiki? For now it's okay, but as a long term solution I would prefer something like [readthedocs](https://readthedocs.org/).

Unquestionably, Javadoc is essential for all future REST developers.

**Comment by Reischi** [comment]
I can't find any documentation. Every single page is shown as you can see in the screen dump.


<img width="1440" alt="bildschirmfoto 2015-09-25 um 09 21 10" src="https://cloud.githubusercontent.com/assets/8338039/10095103/994ba1cc-6367-11e5-85bd-fb4692c5bc6d.png">

**Comment by thomai** [comment]
Since @jqbbq updated the wiki, titles contain the version: [Just use the links on the start page](https://github.com/Fachschaft07/fs-rest/wiki#user-content-version-06) ;-)

**Comment by FHellmann** [comment]
@jqbbq The [module sample](https://github.com/Fachschaft07/fs-rest/wiki/v0.6%20module) does not fit to the url. I think, it would also make sence, to add a sample with and without an id (also at the other interfaces). To see all the possible results.

**Comment by FHellmann** [comment]
The jobs url is still missing and the content of job url is empty.
