### ISSUE TITLE
Small usability enhancement - adding studygroup to timetable

### ISSUE THREAD

**Issue by trampi** [Fachschaft07/fs-rest#41]
Please provide either checkboxes to check the relevant study groups or autocompletion with case insensitive selection of the study group. It took me some seconds to understand that i have to type "IG" instead of "ig".

Thanks for the great app ;-)

**Comment by FHellmann** [comment]
You could tipe "IG" and "ig". This doesn't matter.

**Comment by jqbbq** [comment]
Can not reproduce the Problem, i get an valid response for both versions:
http://fs.cs.hm.edu/rest/api/1/timetable/modules?group=ig
http://fs.cs.hm.edu/rest/api/1/timetable/modules?group=IG

Maybe this is an Problem in the https://github.com/Fachschaft07/fs-app @FHellmann

**Comment by FHellmann** [comment]
This is also possible in the fs-app.

**Comment by trampi** [comment]
Strange. I can not reproduce this anymore. Sorry ;-)
