### ISSUE TITLE
Timetable IB

### ISSUE THREAD

**Issue by barnold89** [Fachschaft07/fs-rest#49]
Fail to parse the timetable Pasing:

http://www.bwl.hm.edu/_sonstiges/vorlesungs_seminarplan/index.de.html
Studiengang:	Wirtschaftsinformatik
Semestergruppe:  	WIF 4 B, WIF 6 B ...

Time is beginning with "BLOCKWOCHE" instead of a valid time format.

**Comment by jqbbq** [comment]
Fixed
