### ISSUE TITLE
NullPointerException on FWP subjects

### ISSUE THREAD

**Issue by FHellmann** [Fachschaft07/fs-rest#55]
Every request to get a FWP subject leads to a NullPointerException.

For example:
https://fs.cs.hm.edu/rest/api/1/timetable/lessons?group=IF&module=technicalwritingincomputerscience&teacher=balazsaniko

Result:
```json
{"errorCode":101,"exception":"java.lang.NullPointerException","message":null,"url":"http://192.168.60.102:9090/rest/api/1/timetable/lessons"}
```

**Comment by jqbbq** [comment]
Fixed and deployed with #56 . The problem was that one of the FWP entries does not have an module assigned but we didn't check for it.
